Abertura do documento de custos.
fga-eps-mds/2023-2-CAPJu-Doc pull request #34
Opened 2023-10-06 23:38 UTC by JongaMatos

## Descrição

Foi criado documento de gerenciamento de custos, onde os mesmos estão separados em:

* Custos semanais ("pagamento" dos desenvolvedores, energia, internet)
* Custos fixos (equipamentos)

## Tipos de Mudanças
- [X] Documentação.

2023-10-07 15:18 UTC, camilacareli commented
Colocar referência, histórico de versão (autores, data, versão e detalhamento) e como este custo é baseado.

2023-10-07 21:29 UTC, brendavsantos requested changes

2023-10-07 21:29 UTC, brendavsantos commented on docs/projeto/custos.md
Colocar introdução do que é um documento de gerenciamento de custos, pq temos que fazer, qual a importância etc

2023-10-07 21:29 UTC, brendavsantos commented on docs/projeto/custos.md
> +Considerando o custo semanal de **R$ 8354,00**, duração de 12 semanas para o projeto, e o custo de **R$ 3.698,00** por membro da equipe, para equipamentos (que não é recorrente e ocorrerá apenas na p
Não sei se considerou isso, mas é bom rever a quantidade de semanas de duração do projeto, em tese ele iniciou desde o primeiro dia de aula e vai terminar no ultimo dia de entrega

2023-10-07 21:29 UTC, brendavsantos commented on docs/projeto/custos.md
> +| 04/09/2023 | 1.0    | Criação do documento | João Gabriel de Matos | A definir   |
Adicionar eu e camila, já que fomos definidas como revisoras

2023-10-11 16:09 UTC, JongaMatos commented on docs/projeto/custos.md
> +Considerando o custo semanal de **R$ 8354,00**, duração de 12 semanas para o projeto, e o custo de **R$ 3.698,00** por membro da equipe, para equipamentos (que não é recorrente e ocorrerá apenas na p
Considerando inicio das aulas no dia 31/07, e conclusão do projeto dia 14/12, contabiliza 19 semanas. Irei corrigir!

2023-10-20 19:54 UTC, brendavsantos approved these changes

2023-10-20 19:55 UTC, merged