Inserção da tabela de disponibilidade dos membros
fga-eps-mds/2023-2-CAPJu-Doc pull request #48
Opened 2023-10-08 01:47 UTC by DaviRogs

## Descrição
Quadro de disponibilidade da equipe adicionado na documentação do projeto

https://fga-eps-mds.github.io/2023-2-CAPJu-Doc/projeto/comunicacao/

## _Issue_ Relacionada

 #39

## Capturas de Tela (se apropriado):

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/95711861/e6d2d024-7e88-46f0-b224-7637fc02258e)

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes);
- [ ] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
- [x] Documentação.

2023-10-08 03:50 UTC, DanielRogs commented
LGTM 🚀

2023-10-08 03:53 UTC, DanielRogs approved these changes
LGTM 🚀

2023-10-08 03:59 UTC, DanielRogs requested changes
Tem um erro no versionamento do arquivo na realidade

2023-10-08 03:59 UTC, DanielRogs commented on docs/projeto/comunicacao.md
> +| 01/10/2023 | 0.1.0 | Criação do documento | Harryson C. Martins/Leandro de A. Oliveira |
Arrumar o Autor da Documentação, que foi você, coloca o seu nome e Sobrenome. Colocar uma nova coluna: Revisores com o meu nome e do Jonga, Que são os revisores pelo GitHub

2023-10-08 04:07 UTC, DanielRogs commented on docs/projeto/comunicacao.md
> +| 01/10/2023 | 0.1.0 | Criação do documento | Harryson C. Martins/Leandro de A. Oliveira |
Padroniza o versionamento tbm. Todos colocaram 1.0 como a primiera versão. Deixa assim mesmo.

2023-10-09 15:07 UTC, DaviRogs reviewed
Correções dos pedidos feitos

2023-10-11 03:56 UTC, DanielRogs approved these changes
LGTM 👍

2023-10-22 01:57 UTC, JongaMatos approved these changes

2023-10-22 01:57 UTC, merged