#56 - Ata da semana 6
fga-eps-mds/2023-2-CAPJu-Doc pull request #57
Opened 2023-10-19 01:50 UTC by DanielRogs

## Descrição

Este pull request trata da documentação da reunião da sexta semana. A primeira versão foi criada em 16/10 durante a reunião que contou com a presença do professor e a ausência do Product Owner, justificando a criação da versão inicial da documentação. A versão 2.0 incorpora as atualizações discutidas durante a reunião subsequente com a participação do P.O. Essas atualizações foram incorporadas ao mesmo arquivo da ata de reunião.

## _Issue_ Relacionada
[#56 - [DOC] Criar Documento de Reunião com o Product Owner da 6⁰ semana.](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/issues/56)

## Capturas de Tela (se apropriado):
![Frame 1](https://i.imgur.com/X4N1j4y.png)
![Frame 2](https://i.imgur.com/dLSvIoU.png)

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes);
- [ ] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
- [x] Documentação.

2023-10-21 17:36 UTC, brendavsantos requested changes

2023-10-21 17:36 UTC, brendavsantos commented on docs/relatorios/semana1/Kick-off.md
> +- **Participantes:** Membros de desenvolvimento do CAPJu
E o PO? Se ele tava junto...

2023-10-22 03:58 UTC, brendavsantos approved these changes

2023-10-22 18:28 UTC, M0tt1nh4 approved these changes

2023-10-22 18:30 UTC, M0tt1nh4 requested changes
Preciso que resolvam os conflitos gerados pela exclusão da ata de kick-off

2023-10-22 18:45 UTC, closed without merging