#40 - Cronograma de dojo
fga-eps-mds/2023-2-CAPJu-Doc pull request #58
Opened 2023-10-19 13:58 UTC by LeanArs

## Descrição
Este pull request trata da documentação do cronograma de dojo. A primeira versão foi criada em 07/10.

## _Issue_ Relacionada
[#40 - [DOC] Adicionar cronograma de dojo](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/issues/40)

## Capturas de Tela (se apropriado):
![Imagem](https://i.imgur.com/v5c4Hb7.png)
![Imagem](https://i.imgur.com/EmboGvo.png)

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes);
- [ ] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
- [x] Documentação.

2023-10-20 03:11 UTC, DaviRogs requested changes
Há dois pequenos probleminhas que visualizei no código Léo, dá uma olhadinha nas minhas revisões.

2023-10-20 03:11 UTC, DaviRogs commented on docs/controle/cronograma_de_dojo.md
> +<iframe width="1250px" height="450px" frameborder="0"width="1250px" height="550px" frameborder="0" src="https://docs.google.com/spreadsheets/d/1iLTA7dNteMGkAFr6mH61mj7gx838MtVl/edit#gid=1062301048"><
O link em que foi gerado para o usuário visualizar está liberado para editar, muda o link para somente visualizar, caso contrário, quaquer um está podendo colocar o registro na planilha diretamente no doc

2023-10-20 03:11 UTC, DaviRogs commented on docs/controle/cronograma_de_dojo.md
> +| 07/10/2023 | 1.0 | Criação do Documento | Leandro Almeida |
Adiciona os revisores do Pul aqui também

2023-10-20 03:13 UTC, DaviRogs commented
Seria interessante também só colocar uma peqauena introdução da página, apenas uma recomendação, okay?

2023-10-20 03:33 UTC, DaviRogs commented on docs/controle/cronograma_de_dojo.md
> +<iframe width="1250px" height="450px" frameborder="0"width="1250px" height="550px" frameborder="0" src="https://docs.google.com/spreadsheets/d/1iLTA7dNteMGkAFr6mH61mj7gx838MtVl/edit?usp=sharing&ouid=
Agora está tudo certinho!

2023-10-20 03:33 UTC, DaviRogs approved these changes

2023-10-21 14:47 UTC, Denniel-sudo approved these changes

2023-10-21 14:48 UTC, merged