Criando semana 7 e corrigindo semana 6
fga-eps-mds/2023-2-CAPJu-Doc pull request #79
Opened 2023-10-31 02:46 UTC by DanielRogs

## Descrição

## _Issue_ Relacionada

## Como Isso Foi Testado?

## Capturas de Tela (se apropriado):

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes);
- [ ] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
- [ ] Documentação.

2023-11-02 15:36 UTC, WashingtonBispo approved these changes

2023-11-02 15:43 UTC, M0tt1nh4 requested changes

2023-11-02 15:43 UTC, M0tt1nh4 commented on docs/relatorios/semana7/semana7.md
> +    - As funcionalidades sob pendência, apesa de terem feitas, não foram implementadas;
Elas foram Implementadas porém não foram implantadas.

2023-11-04 19:14 UTC, DanielRogs commented on docs/relatorios/semana7/semana7.md
> +    - As funcionalidades sob pendência, apesa de terem feitas, não foram implementadas;
@M0tt1nh4, corrigido

2023-11-04 19:16 UTC, M0tt1nh4 approved these changes

2023-11-04 19:44 UTC, merged