Adicionando valores dos riscos obtidos nas semanas 1 a 7 e sprints 1 a 3
fga-eps-mds/2023-2-CAPJu-Doc pull request #81
Opened 2023-11-02 13:53 UTC by brendavsantos

## Descrição
Foram detalhados os valores dos riscos obtidos nas semanas 1 a 7 (período pré-sprints) e sprints 1 a 3 do projeto.

## _Issue_ Relacionada

## Como Isso Foi Testado?
Foi testado subindo o mkdocs pra evitar que erros no markdown pudessem acontecer (na visualização das tabelas etc)

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes);
- [ ] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
- [ x ] Documentação.

2023-11-02 15:26 UTC, LeanArs commented
Necessário adicionar quebra de linha nos riscos R04, R05, R07, R08 e R14.

2023-11-02 15:28 UTC, LeanArs requested changes
Necessário adicionar quebra de linha nos riscos R04, R05, R07, R08 e R14.

2023-11-02 17:41 UTC, camilacareli commented
Melhoria do texto "Como foi testado?": "Para garantir a ausência de erros no markdown, como a formatação de tabelas, o procedimento envolveu o upload do mkdocs."

2023-11-05 23:20 UTC, brendavsantos commented
> Necessário adicionar quebra de linha nos riscos R04, R05, R07, R08 e R14.
 Feito

2023-11-06 14:24 UTC, LeanArs approved these changes

2023-11-09 13:14 UTC, merged