Ata sprint 3
fga-eps-mds/2023-2-CAPJu-Doc pull request #83
Opened 2023-11-04 03:21 UTC by EhOBruno

## Descrição

Esse PR inclui a Review e Planning da sprint 03.

## _Issue_ Relacionada
Inexistente.

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes);
- [ ] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
- [x] Documentação.

2023-11-05 23:37 UTC, Denniel-sudo requested changes

2023-11-05 23:37 UTC, Denniel-sudo commented on docs/relatorios/sprints/sprint03/review.md
> +**Data de Início:** 14/10/2023 <br/>
Precisa ajustar a data de início e termino

2023-11-06 16:31 UTC, WashingtonBispo approved these changes

2023-11-11 17:01 UTC, Denniel-sudo approved these changes

2023-11-12 13:15 UTC, merged