Review da sprint 4
fga-eps-mds/2023-2-CAPJu-Doc pull request #84
Opened 2023-11-04 19:31 UTC by AmandaaMoura

## Descrição

Esse PR inclui a Review da sprint 04 e uma imagem do board construido nesta reunião

## _Issue_ Relacionada
Inexistente.

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes);
- [ ] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
- [x] Documentação.

2023-11-05 23:27 UTC, brendavsantos requested changes

2023-11-05 23:27 UTC, brendavsantos commented on docs/sprints/sprint04/review.md
> +![](<Captura de tela 2023-11-04 144256.png>)
Coloca um nome dentro do [ ], é uma boa prática pra caso a imagem não carregue (em todas as imagens)

2023-11-05 23:27 UTC, brendavsantos commented on docs/sprints/sprint04/review.md
> +**Pontuação:** x <br/>
Procura discutir com a galera uma pontuação ou perguntar pra ele a nota que ele atrelaria a essa tarefa e as demais que são dele pra não ficar sem

2023-11-11 19:36 UTC, camilacareli commented on docs/sprints/sprint04/review.md
Colocar o motivo de não ter sido finalizada tal issue e ainda colocar qual foi o membro de EPS que ficou responsável por supervisionar tal US.

2023-11-11 19:37 UTC, camilacareli requested changes
Colocar o motivo de não ter sido finalizada tal issue e ainda colocar qual foi o membro de EPS que ficou responsável por supervisionar tal US.

2023-11-18 18:12 UTC, AmandaaMoura commented on docs/sprints/sprint04/review.md
> +![](<Captura de tela 2023-11-04 144256.png>)
ok

2023-11-18 18:13 UTC, AmandaaMoura commented on docs/sprints/sprint04/review.md
> +**Pontuação:** x <br/>
ok

2023-11-18 18:44 UTC, brendavsantos approved these changes

2023-11-18 20:00 UTC, camilacareli approved these changes

2023-11-18 20:01 UTC, merged