Criacao da ata da planning, da review e da retro
fga-eps-mds/2023-2-CAPJu-Doc pull request #88
Opened 2023-11-11 19:24 UTC by camilacareli

## Descrição

## _Issue_ Relacionada

## Como Isso Foi Testado?

## Capturas de Tela (se apropriado):

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes);
- [ ] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
- [ ] Documentação.

2023-11-13 14:23 UTC, M0tt1nh4 commented on docs/relatorios/sprints/sprint05/planning05.md
> +**Número da Sprint:** 5 <br/>
Verificar o número da Sprint, pois a planning da Sprint 5 não faz sentido ocorrer no mesmo dia da review e da retro da mesma.

2023-11-13 14:25 UTC, M0tt1nh4 requested changes
Arrume onde está comentado por favor

2023-11-13 14:25 UTC, M0tt1nh4 commented on docs/relatorios/sprints/sprint05/planning05.md
> +Tarefa nao entregue: us4 e 06 anmmanjsb jnsm
acrdito que os nomes estejam errados, arrume eles por favor.

2023-11-13 14:25 UTC, M0tt1nh4 commented on docs/relatorios/sprints/sprint05/planning05.md
> +**Número da Sprint:** 5 <br/>
Verificar o número da Sprint, pois a planning da Sprint 5 não faz sentido ocorrer no mesmo dia da review e da retro da mesma.

2023-11-17 13:25 UTC, JongaMatos requested changes
Adicione os documentos no arquivo mkdocs.yml

2023-11-20 19:14 UTC, JongaMatos approved these changes

2023-11-20 19:30 UTC, M0tt1nh4 approved these changes

2023-11-20 19:54 UTC, merged