Review, Retro e Planning da Sprint 06.
fga-eps-mds/2023-2-CAPJu-Doc pull request #93
Opened 2023-11-18 18:46 UTC by M0tt1nh4

## Descrição
Ata da reunião de review e retro da sprint 06 e a planning da sprint 07

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes);
- [ ] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
- [x] Documentação.

2023-11-18 20:27 UTC, brendavsantos requested changes

2023-11-18 20:27 UTC, brendavsantos commented on docs/relatorios/sprints/sprint06/planning.md
> +| 018/11/2023 | 1.0 | Criação do Documento | Felipe de Oliveira Motta | Washington Bispo e Brenda Vitória |
data ta 018

2023-11-18 20:27 UTC, brendavsantos commented on docs/relatorios/sprints/sprint06/planning.md
> +**Número da Sprint:** 7 <br/>
O arquivo ta dentro da sprint 6 mas o planejamento é da 7? Vê ai...

2023-11-18 21:07 UTC, M0tt1nh4 commented on docs/relatorios/sprints/sprint06/planning.md
> +**Número da Sprint:** 7 <br/>
isso, pq a planning eh pra essa de 19 ate 25, mas foi feita no dia de hj dentro da sprint 6, segui o padrão que estavam colocando

2023-11-19 00:26 UTC, brendavsantos approved these changes

2023-11-19 00:26 UTC, merged